#!/bin/bash

echo -e "\033[0;32m INFO \033[0m Hellolin's cleaning util for competitive programming."
echo -e ""

echo -e "\033[0;32m INFO \033[0m Starting to delete binary files that generated by standard compilation..."
find $(git rev-parse --show-toplevel) -type f -name '*.exe' -print -exec rm {} \;
find $(git rev-parse --show-toplevel) -type f -name '*.bin' -print -exec rm {} \;
echo -e "\033[0;32m INFO \033[0m Success."
echo -e ""

echo -e "\033[0;32m INFO \033[0m Starting to delete temp binary files..."
find $(git rev-parse --show-toplevel) -type f -name 'tempCodeRunnerFile*' -print -exec rm {} \;
find $(git rev-parse --show-toplevel) -type f -name '*.tmp' -print -exec rm {} \;
echo -e "\033[0;32m INFO \033[0m Success."
echo -e ""

